// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    ACard: typeof import('@arco-design/web-vue')['Card']
    ACol: typeof import('@arco-design/web-vue')['Col']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AInput: typeof import('@arco-design/web-vue')['Input']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    AList: typeof import('@arco-design/web-vue')['List']
    AListItem: typeof import('@arco-design/web-vue')['ListItem']
    AListItemMeta: typeof import('@arco-design/web-vue')['ListItemMeta']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ASlider: typeof import('@arco-design/web-vue')['Slider']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ATypographyParagraph: typeof import('@arco-design/web-vue')['TypographyParagraph']
    CilLoop: typeof import('./../components/icons/CilLoop.vue')['default']
    CilLoop1: typeof import('./../components/icons/CilLoop1.vue')['default']
    CilLoopCircular: typeof import('./../components/icons/CilLoopCircular.vue')['default']
    IcRoundLyrics: typeof import('./../components/icons/IcRoundLyrics.vue')['default']
    LyricPanel: typeof import('./../components/LyricPanel.vue')['default']
    MdiPlaylistMusic: typeof import('./../components/icons/MdiPlaylistMusic.vue')['default']
    Player: typeof import('./../components/player.vue')['default']
    PlayList: typeof import('./../components/PlayList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongTypesetting: typeof import('./../components/SongTypesetting.vue')['default']
    TablerError404: typeof import('./../components/icons/TablerError404.vue')['default']
  }
}

export {}
