// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CilLoop: typeof import('./../components/icons/CilLoop.vue')['default']
    CilLoop1: typeof import('./../components/icons/CilLoop1.vue')['default']
    CilLoopCircular: typeof import('./../components/icons/CilLoopCircular.vue')['default']
    FxemojiFirstquartermoonface: typeof import('./../components/icons/FxemojiFirstquartermoonface.vue')['default']
    IcRoundArrowLeft: typeof import('./../components/v-dropdown/icons/IcRoundArrowLeft.vue')['default']
    IcRoundChevronLeft: typeof import('./../components/icons/IcRoundChevronLeft.vue')['default']
    IcRoundChevronRight: typeof import('./../components/icons/IcRoundChevronRight.vue')['default']
    IcRoundClear: typeof import('./../components/v-input/icons/IcRoundClear.vue')['default']
    IcRoundExpandLess: typeof import('./../components/player/icons/IcRoundExpandLess.vue')['default']
    IcRoundFavorite: typeof import('./../components/player/icons/IcRoundFavorite.vue')['default']
    IcRoundFavoriteBorder: typeof import('./../components/player/icons/IcRoundFavoriteBorder.vue')['default']
    IcRoundPause: typeof import('./../components/player/icons/IcRoundPause.vue')['default']
    IcRoundPerson: typeof import('./../components/icons/IcRoundPerson.vue')['default']
    IcRoundPlayArrow: typeof import('./../components/player/icons/IcRoundPlayArrow.vue')['default']
    IcRoundQueueMusic: typeof import('./../components/player/icons/IcRoundQueueMusic.vue')['default']
    IcRoundReadMore: typeof import('./../components/icons/IcRoundReadMore.vue')['default']
    IcRoundSearch: typeof import('./../components/v-input/icons/IcRoundSearch.vue')['default']
    IcRoundSkipNext: typeof import('./../components/player/icons/IcRoundSkipNext.vue')['default']
    IcRoundSkipPrevious: typeof import('./../components/player/icons/IcRoundSkipPrevious.vue')['default']
    IcRoundVolumeOff: typeof import('./../components/player/icons/IcRoundVolumeOff.vue')['default']
    IcRoundVolumeUp: typeof import('./../components/player/icons/IcRoundVolumeUp.vue')['default']
    IcTwotoneAutoAwesome: typeof import('./../components/player/icons/IcTwotoneAutoAwesome.vue')['default']
    LineMdGithubTwotone: typeof import('./../components/icons/LineMdGithubTwotone.vue')['default']
    LyricPanel: typeof import('./../components/player/lyric-panel/index.vue')['default']
    MdiPlaylistMusic: typeof import('./../components/icons/MdiPlaylistMusic.vue')['default']
    NotoV1FullMoonFace: typeof import('./../components/icons/NotoV1FullMoonFace.vue')['default']
    Player: typeof import('./../components/player/index.vue')['default']
    PlayList: typeof import('./../components/player/play-list/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongTypesetting: typeof import('./../components/song-typesetting/index.vue')['default']
    TablerError404: typeof import('./../components/icons/TablerError404.vue')['default']
    VCard: typeof import('./../components/v-card/index.vue')['default']
    VDropdown: typeof import('./../components/v-dropdown/index.vue')['default']
    VInput: typeof import('./../components/v-input/index.vue')['default']
    VList: typeof import('./../components/v-list/index.vue')['default']
    VProgress: typeof import('./../components/v-progress/index.vue')['default']
    VSlider: typeof import('./../components/v-slider/index.vue')['default']
  }
}
