// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CilLoop: typeof import('./../components/icons/CilLoop.vue')['default']
    CilLoop1: typeof import('./../components/icons/CilLoop1.vue')['default']
    CilLoopCircular: typeof import('./../components/icons/CilLoopCircular.vue')['default']
    FxemojiFirstquartermoonface: typeof import('./../components/icons/FxemojiFirstquartermoonface.vue')['default']
    IcRoundArrowLeft: typeof import('./../components/v-dropdown/icons/IcRoundArrowLeft.vue')['default']
    IcRoundChevronLeft: typeof import('./../components/icons/IcRoundChevronLeft.vue')['default']
    IcRoundChevronRight: typeof import('./../components/icons/IcRoundChevronRight.vue')['default']
    IcRoundClear: typeof import('./../components/v-input/icons/IcRoundClear.vue')['default']
    IcRoundLyrics: typeof import('./../components/icons/IcRoundLyrics.vue')['default']
    IcRoundPerson: typeof import('./../components/icons/IcRoundPerson.vue')['default']
    IcRoundPlayArrow: typeof import('./../components/icons/IcRoundPlayArrow.vue')['default']
    IcRoundReadMore: typeof import('./../components/icons/IcRoundReadMore.vue')['default']
    IcRoundSearch: typeof import('./../components/v-input/icons/IcRoundSearch.vue')['default']
    LineMdGithubTwotone: typeof import('./../components/icons/LineMdGithubTwotone.vue')['default']
    LyricPanel: typeof import('./../components/player/lyric-panel/index.vue')['default']
    MdiPlaylistMusic: typeof import('./../components/icons/MdiPlaylistMusic.vue')['default']
    NotoV1FullMoonFace: typeof import('./../components/icons/NotoV1FullMoonFace.vue')['default']
    Player: typeof import('./../components/player/index.vue')['default']
    PlayList: typeof import('./../components/player/play-list/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongTypesetting: typeof import('./../components/song-typesetting.vue')['default']
    TablerError404: typeof import('./../components/icons/TablerError404.vue')['default']
    VDropdown: typeof import('./../components/v-dropdown/index.vue')['default']
    VInput: typeof import('./../components/v-input/index.vue')['default']
  }
}

export {}
